name: Build LaTeX document
on:
  push:
    tags:
      - "*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Generate Git tex info
        run: make prepare
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          args: -jobname=cto-framework-book -output-format=pdf
          latexmk_use_lualatex: true
          root_file: cto-framework-book.tex
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            cto-framework-book.pdf
